package com.moxtra.bot.model;

public enum EventType {
	MESSAGE, BOT_INSTALLED, BOT_UNINSTALLED, POSTBACK, ACCOUNT_LINK, ACCESS_TOKEN, PAGE_CREATED,
	PAGE_ANNOTATED, FILE_UPLOADED, TODO_CREATED, TODO_COMPLETED, MEET_RECORDING_READY  
}
